name: 'Setup Python Environment'
description: 'Checkout and setup python 3.11'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11" #Lambda runtime is 3.11, so we lint against that for consistency.